import React from 'react'
import ReactDOM from 'react-dom'

// This will be the object populated
const components = {}

// Here, we load the files from the `app/javascript/components` folder
const context = require.context('../components', false, /\.jsx$/)
for (const key of context.keys()) {
  // Extract component name from the file path with a regular expression
  // `../components/Hello.jsx` becomes `Hello`
  const componentName = key.match(/([^/.]+)\.jsx/)[1]

  // e.g. components['Hello'] = Hello component definition
  components[componentName] = context(key).default
}

document.addEventListener('DOMContentLoaded', () => {
  // Get all tags generated by the `rails_component` helper.
  const mountingElements = document.querySelectorAll('[data-react-component]')

  for (const element of mountingElements) {
    // Extract name and props from the data present in the element
    const { name, props } = JSON.parse(element.getAttribute('data-react-component'))

    // Retrieve the component from the `components` object we mounted before,
    // and check if it exists.
    const component = components[name]
    if (!component) {
      console.log(`Component ${name} not found`)
      continue
    }

    // Mount the component with the props inside the element
    ReactDOM.render(
      React.createElement(component, props || {}),
      element
    )
  }
})
